### ISSUE TITLE
error-message behaves differently when a symbol is passed

### ISSUE THREAD

**Issue by swiknaba** [micke/valid_email2#143]
while this:

```ruby
validates :email, 'valid_email_2/email': { message: "is not a valid email" }
```

will render `"is not a valid email"` (no surprise)

the following:

```ruby
validates :email, 'valid_email_2/email': { message: :foo }
```

seems to look up the rails translations, since it renders me:

`"translation missing: en.activerecord.errors.models.user.attributes.email.foo"`

which was quite a surprise!

If that is intended, it would be awesome to have it in the readme. Else that is a bug?

I quickly wrote a spec for it as proof, you can check it out here: https://github.com/swiknaba/valid_email2/blob/swiknaba/message-as-symbol/spec/valid_email2_spec.rb#L235

here the output from rspec:

```
MacBook-Pro:valid_email2 ry$ bundle exec rspec -b
..............................F..

Failures:

  1) ValidEmail2 with custom error message when message is passed as symbol supports settings a custom error message
     Failure/Error: expect(user.errors.full_messages).to include("custom_message")
       expected ["Email translation missing: en.activemodel.errors.models.test_user_message_as_symbol.attributes.email.custom_message"] to include "custom_message"
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-support-3.5.0/lib/rspec/support.rb:87:in `block in <module:Support>'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-support-3.5.0/lib/rspec/support.rb:96:in `notify_failure'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/fail_with.rb:27:in `fail_with'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.5.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/valid_email2_spec.rb:239:in `block (4 levels) in <top (required)>'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `instance_exec'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `block in run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `block in with_around_and_singleton_context_hooks'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `block in with_around_example_hooks'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `block in run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `with_around_example_hooks'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `with_around_and_singleton_context_hooks'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:251:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `map'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:589:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `block in run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `map'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `block in run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `map'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (3 levels) in run_specs'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `map'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (2 levels) in run_specs'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1835:in `with_suite_hooks'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:87:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
     # /Users/ry/.rbenv/versions/2.6.5/bin/rspec:23:in `load'
     # /Users/ry/.rbenv/versions/2.6.5/bin/rspec:23:in `<top (required)>'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /Users/ry/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
     # /Users/ry/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
     # /Users/ry/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'

Finished in 0.89179 seconds (files took 0.37448 seconds to load)
33 examples, 1 failure

Failed examples:

rspec ./spec/valid_email2_spec.rb:236 # ValidEmail2 with custom error message when message is passed as symbol supports settings a custom error message
```

**Comment by micke** [comment]
This isn't something that has to two with valid_email2 per se.
It's a rails feature, see https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-add
